/**
 * OpenAPI WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { SensorData } from '../model/sensorData';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {CookieService} from "ngx-cookie-service";


@Injectable()
export class AnalyticService {

    protected basePath = 'http://192.168.15.34:8010';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, private cookieService: CookieService,@Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param sensorId
     * @param key
     * @param threshold
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAnomalies(sensorId: string, key: string, threshold?: number, observe?: 'body', reportProgress?: boolean): Observable<Array<SensorData>>;
    public getAnomalies(sensorId: string, key: string, threshold?: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SensorData>>>;
    public getAnomalies(sensorId: string, key: string, threshold?: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SensorData>>>;
    public getAnomalies(sensorId: string, key: string, threshold?: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAnomalies.');
        }

        if (key === null || key === undefined) {
            throw new Error('Required parameter key was null or undefined when calling getAnomalies.');
        }


        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (key !== undefined && key !== null) {
            queryParameters = queryParameters.set('key', <any>key);
        }
        if (threshold !== undefined && threshold !== null) {
            queryParameters = queryParameters.set('threshold', <any>threshold);
        }

        let headers = this.defaultHeaders;

      // authentication (bearerAuth) required
      if (this.cookieService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.cookieService.get("token")
          : this.cookieService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SensorData>>('get',`${this.basePath}/v1/sensor/${encodeURIComponent(String(sensorId))}/anomalies`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param key
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPrediction(sensorId: string, key: string, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: any; }>;
    public getPrediction(sensorId: string, key: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: any; }>>;
    public getPrediction(sensorId: string, key: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: any; }>>;
    public getPrediction(sensorId: string, key: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getPrediction.');
        }

        if (key === null || key === undefined) {
            throw new Error('Required parameter key was null or undefined when calling getPrediction.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (key !== undefined && key !== null) {
            queryParameters = queryParameters.set('key', <any>key);
        }

        let headers = this.defaultHeaders;
      // authentication (bearerAuth) required
      if (this.cookieService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.cookieService.get("token")
          : this.cookieService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<{ [key: string]: any; }>('get',`${this.basePath}/v1/sensor/${encodeURIComponent(String(sensorId))}/predict`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param key
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPublicPrediction(sensorId: string, key: string, observe?: 'body', reportProgress?: boolean): Observable<{ [key: string]: any; }>;
    public getPublicPrediction(sensorId: string, key: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<{ [key: string]: any; }>>;
    public getPublicPrediction(sensorId: string, key: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<{ [key: string]: any; }>>;
    public getPublicPrediction(sensorId: string, key: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getPublicPrediction.');
        }

        if (key === null || key === undefined) {
            throw new Error('Required parameter key was null or undefined when calling getPublicPrediction.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (key !== undefined && key !== null) {
            queryParameters = queryParameters.set('key', <any>key);
        }

        let headers = this.defaultHeaders;

      // authentication (bearerAuth) required
      if (this.cookieService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.cookieService.get("token")
          : this.cookieService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

      // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<{ [key: string]: any; }>('get',`${this.basePath}/v1/sensor/public/${encodeURIComponent(String(sensorId))}/predict`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param key
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPublicSensorTrend(sensorId: string, key: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SensorData>>;
    public getPublicSensorTrend(sensorId: string, key: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SensorData>>>;
    public getPublicSensorTrend(sensorId: string, key: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SensorData>>>;
    public getPublicSensorTrend(sensorId: string, key: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getPublicSensorTrend.');
        }

        if (key === null || key === undefined) {
            throw new Error('Required parameter key was null or undefined when calling getPublicSensorTrend.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (key !== undefined && key !== null) {
            queryParameters = queryParameters.set('key', <any>key);
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SensorData>>('get',`${this.basePath}/v1/sensor/public/${encodeURIComponent(String(sensorId))}/trend`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param key
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getSensorTrend(sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<Array<SensorData>>;
    public getSensorTrend(sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<SensorData>>>;
    public getSensorTrend(sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<SensorData>>>;
    public getSensorTrend(sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getSensorTrend.');
        }



        let headers = this.defaultHeaders;

      if (this.cookieService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.cookieService.get("token")
          : this.cookieService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<Array<SensorData>>('get',`${this.basePath}/v1/sensor/${encodeURIComponent(String(sensorId))}/trend`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
