/**
 * OpenAPi WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { DateDto } from '../model/dateDto';
import { NewSensorDataDto } from '../model/newSensorDataDto';
import { SensorData } from '../model/sensorData';
import { SensorDataDto } from '../model/sensorDataDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {SensorDataInterestAreaDto} from "../model/SensorDataInterestAreaDto";
import {CookieService} from "ngx-cookie-service";


@Injectable()
export class SensorDataService {

    protected basePath = 'http://192.168.15.34:8010';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, private CookiesService: CookieService, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteSensorData(id: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public deleteSensorData(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public deleteSensorData(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public deleteSensorData(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling deleteSensorData.');
        }

        let headers = this.defaultHeaders;

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }


      // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('delete',`${this.basePath}/v1/SensorData/private/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

  /**
   *
   *
   * @param interestAreaId
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getLastPublicSensorDataByInterestAreaId(interestAreaId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
  public getLastPublicSensorDataByInterestAreaId(interestAreaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
  public getLastPublicSensorDataByInterestAreaId(interestAreaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
  public getLastPublicSensorDataByInterestAreaId(interestAreaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (interestAreaId === null || interestAreaId === undefined) {
      throw new Error('Required parameter interestAreaId was null or undefined when calling getLastPublicSensorDataByInterestAreaId.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer Authentication) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/public/top-by-interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

    /**
     *
     *
     * @param interestAreaId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataByInterestAreaId10Min(interestAreaId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataByInterestAreaId10Min(interestAreaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataByInterestAreaId10Min(interestAreaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataByInterestAreaId10Min(interestAreaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getAllPrivateSensorDataByInterestAreaId10Min.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/10m/interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataByInterestAreaId15Min(interestAreaId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataByInterestAreaId15Min(interestAreaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataByInterestAreaId15Min(interestAreaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataByInterestAreaId15Min(interestAreaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getAllPrivateSensorDataByInterestAreaId15Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/15/interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataByInterestAreaId5Min(interestAreaId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataByInterestAreaId5Min(interestAreaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataByInterestAreaId5Min(interestAreaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataByInterestAreaId5Min(interestAreaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getAllPrivateSensorDataByInterestAreaId5Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/5/interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensor10Min(sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensor10Min(sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensor10Min(sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensor10Min(sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAllPrivateSensorDataBySensor10Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/10/sensorId/${encodeURIComponent(String(sensorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensor15Min(sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensor15Min(sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensor15Min(sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensor15Min(sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAllPrivateSensorDataBySensor15Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/15/sensorId/${encodeURIComponent(String(sensorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensor5Min(sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensor5Min(sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensor5Min(sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensor5Min(sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAllPrivateSensorDataBySensor5Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/5/sensorId/${encodeURIComponent(String(sensorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensorAndInterestAreaId10Min(interestAreaId: string, sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId10Min(interestAreaId: string, sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId10Min(interestAreaId: string, sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId10Min(interestAreaId: string, sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getAllPrivateSensorDataBySensorAndInterestAreaId10Min.');
        }

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAllPrivateSensorDataBySensorAndInterestAreaId10Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/10/sensor/${encodeURIComponent(String(sensorId))}/interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensorAndInterestAreaId15Min(interestAreaId: string, sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId15Min(interestAreaId: string, sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId15Min(interestAreaId: string, sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId15Min(interestAreaId: string, sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getAllPrivateSensorDataBySensorAndInterestAreaId15Min.');
        }

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAllPrivateSensorDataBySensorAndInterestAreaId15Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/15/sensor/${encodeURIComponent(String(sensorId))}/interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensorAndInterestAreaId5Min(interestAreaId: string, sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId5Min(interestAreaId: string, sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId5Min(interestAreaId: string, sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorAndInterestAreaId5Min(interestAreaId: string, sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getAllPrivateSensorDataBySensorAndInterestAreaId5Min.');
        }

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getAllPrivateSensorDataBySensorAndInterestAreaId5Min.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/last/5/sensor/${encodeURIComponent(String(sensorId))}/interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPrivateSensorDataBySensorBetweenDate(body: DateDto, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPrivateSensorDataBySensorBetweenDate(body: DateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorBetweenDate(body: DateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPrivateSensorDataBySensorBetweenDate(body: DateDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling getAllPrivateSensorDataBySensorBetweenDate.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SensorDataInterestAreaDto>('post',`${this.basePath}/v1/SensorData/private/date/sensor`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }


  /**
   *
   *
   * @param body
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAllPublicSensorDataBySensorBetweenDate(body: DateDto, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
  public getAllPublicSensorDataBySensorBetweenDate(body: DateDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
  public getAllPublicSensorDataBySensorBetweenDate(body: DateDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
  public getAllPublicSensorDataBySensorBetweenDate(body: DateDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling getAllPrivateSensorDataBySensorBetweenDate.');
    }

    let headers = this.defaultHeaders;

    // authentication (Bearer Authentication) required
    if (this.configuration.accessToken) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.configuration.accessToken()
        : this.configuration.accessToken;
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<SensorDataInterestAreaDto>('post',`${this.basePath}/v1/SensorData/public/date/sensor`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPublicSensorDataIn10Min(observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPublicSensorDataIn10Min(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataIn10Min(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataIn10Min(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/public/last/10`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPublicSensorDataIn15Min(observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPublicSensorDataIn15Min(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataIn15Min(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataIn15Min(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/public/last/15`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPublicSensorDataIn5Min(observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPublicSensorDataIn5Min(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataIn5Min(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataIn5Min(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/public/last/5`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getAllPublicSensorDataOnTop(observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getAllPublicSensorDataOnTop(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataOnTop(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getAllPublicSensorDataOnTop(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/public/top`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLastPrivateSensorDataByInterestAreaId(interestAreaId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getLastPrivateSensorDataByInterestAreaId(interestAreaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getLastPrivateSensorDataByInterestAreaId(interestAreaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getLastPrivateSensorDataByInterestAreaId(interestAreaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getLastPrivateSensorDataByInterestAreaId.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/top-by-interestAreaId/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLastPrivateSensorDataBySensor(sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getLastPrivateSensorDataBySensor(sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getLastPrivateSensorDataBySensor(sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getLastPrivateSensorDataBySensor(sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getLastPrivateSensorDataBySensor.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/top-by-sensorId/${encodeURIComponent(String(sensorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param sensorId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getLastPrivateSensorDataBySensorAndInterestAreaId(interestAreaId: string, sensorId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getLastPrivateSensorDataBySensorAndInterestAreaId(interestAreaId: string, sensorId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getLastPrivateSensorDataBySensorAndInterestAreaId(interestAreaId: string, sensorId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getLastPrivateSensorDataBySensorAndInterestAreaId(interestAreaId: string, sensorId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getLastPrivateSensorDataBySensorAndInterestAreaId.');
        }

        if (sensorId === null || sensorId === undefined) {
            throw new Error('Required parameter sensorId was null or undefined when calling getLastPrivateSensorDataBySensorAndInterestAreaId.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/top-by-sensor-interestAreaId/${encodeURIComponent(String(interestAreaId))}/${encodeURIComponent(String(sensorId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param interestAreaId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPrivateSensorDataByInterestArea(interestAreaId: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataInterestAreaDto>;
    public getPrivateSensorDataByInterestArea(interestAreaId: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataInterestAreaDto>>;
    public getPrivateSensorDataByInterestArea(interestAreaId: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataInterestAreaDto>>;
    public getPrivateSensorDataByInterestArea(interestAreaId: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (interestAreaId === null || interestAreaId === undefined) {
            throw new Error('Required parameter interestAreaId was null or undefined when calling getPrivateSensorDataByInterestArea.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataInterestAreaDto>('get',`${this.basePath}/v1/SensorData/private/area/${encodeURIComponent(String(interestAreaId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param id
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPrivateSensorDataBySensorId(id: string, observe?: 'body', reportProgress?: boolean): Observable<SensorDataDto>;
    public getPrivateSensorDataBySensorId(id: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorDataDto>>;
    public getPrivateSensorDataBySensorId(id: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorDataDto>>;
    public getPrivateSensorDataBySensorId(id: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (id === null || id === undefined) {
            throw new Error('Required parameter id was null or undefined when calling getPrivateSensorDataBySensorId.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<SensorDataDto>('get',`${this.basePath}/v1/SensorData/private/Sensor/${encodeURIComponent(String(id))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param type
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getPublicProcessedDataByType(type: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public getPublicProcessedDataByType(type: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public getPublicProcessedDataByType(type: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public getPublicProcessedDataByType(type: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (type === null || type === undefined) {
            throw new Error('Required parameter type was null or undefined when calling getPublicProcessedDataByType.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<string>('get',`${this.basePath}/v1/SensorData/public/processed/${encodeURIComponent(String(type))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Receive sensor data
     * Receive and save sensor data from micro-service
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public receiveSensorData(body: NewSensorDataDto, observe?: 'body', reportProgress?: boolean): Observable<SensorData>;
    public receiveSensorData(body: NewSensorDataDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorData>>;
    public receiveSensorData(body: NewSensorDataDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorData>>;
    public receiveSensorData(body: NewSensorDataDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling receiveSensorData.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }
      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        return this.httpClient.request<SensorData>('post',`${this.basePath}/v1/sensorData`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Save sensor data
     * Save new sensor data with optional file
     * @param data
     * @param file
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveSensorDataForm(data?: NewSensorDataDto, file?: Blob, observe?: 'body', reportProgress?: boolean): Observable<SensorData>;
    public saveSensorDataForm(data?: NewSensorDataDto, file?: Blob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorData>>;
    public saveSensorDataForm(data?: NewSensorDataDto, file?: Blob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorData>>;
    public saveSensorDataForm(data?: NewSensorDataDto, file?: Blob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'multipart/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (data !== undefined) {
            formParams = formParams.append('data', <any>data) as any || formParams;
        }
        if (file !== undefined) {
            formParams = formParams.append('file', <any>file) as any || formParams;
        }

        return this.httpClient.request<SensorData>('post',`${this.basePath}/v1/SaveSensorData`,
            {
                body: convertFormParamsToString ? formParams.toString() : formParams,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateSensorData(body: NewSensorDataDto, observe?: 'body', reportProgress?: boolean): Observable<SensorData>;
    public updateSensorData(body: NewSensorDataDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SensorData>>;
    public updateSensorData(body: NewSensorDataDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SensorData>>;
    public updateSensorData(body: NewSensorDataDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateSensorData.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<SensorData>('put',`${this.basePath}/v1/SensorData/private`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
