/**
 * OpenAPI WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { NewUserDto } from '../model/newUserDto';
import { UserDto } from '../model/userDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';
import {CookieService} from "ngx-cookie-service";


@Injectable()
export class UserService {

    protected basePath = 'http://192.168.15.34:8010';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string,private CookiesService: CookieService, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     *
     *
     * @param body
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addUser(body: NewUserDto, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public addUser(body: NewUserDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public addUser(body: NewUserDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public addUser(body: NewUserDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling addUser.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UserDto>('post',`${this.basePath}/v1/user/newUser`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     *
     *
     * @param email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteUser(email: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public deleteUser(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public deleteUser(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public deleteUser(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling deleteUser.');
        }

        let headers = this.defaultHeaders;

        // authentication (Bearer Authentication) required
        if (this.configuration.accessToken) {
            const accessToken = typeof this.configuration.accessToken === 'function'
                ? this.configuration.accessToken()
                : this.configuration.accessToken;
            headers = headers.set('Authorization', 'Bearer ' + accessToken);
        }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<any>('delete',`${this.basePath}/v1/users/admin${encodeURIComponent(String(email))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }





  /**
   * this is the list of user
   * Get endpoint for user
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getUser(observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
  public getUser(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
  public getUser(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
  public getUser(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    return this.httpClient.request<UserDto>('get',`${this.basePath}/v1/user/private`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

    /**
     *
     *
     * @param body
     * @param email
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public updateUser(body: UserDto, email: string, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
    public updateUser(body: UserDto, email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
    public updateUser(body: UserDto, email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
    public updateUser(body: UserDto, email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (body === null || body === undefined) {
            throw new Error('Required parameter body was null or undefined when calling updateUser.');
        }

        if (email === null || email === undefined) {
            throw new Error('Required parameter email was null or undefined when calling updateUser.');
        }

        let headers = this.defaultHeaders;

      // authentication (bearerAuth) required
      if (this.CookiesService.get("token")) {
        const accessToken = typeof this.configuration.accessToken === 'function'
          ? this.CookiesService.get("token")
          : this.CookiesService.get("token");
        headers = headers.set('Authorization', 'Bearer ' + accessToken);
      }
        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.request<UserDto>('put',`${this.basePath}/v1/user/${encodeURIComponent(String(email))}`,
            {
                body: body,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

  public updatePrivateUser(body: UserDto,  observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
  public updatePrivateUser(body: UserDto,  observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
  public updatePrivateUser(body: UserDto,  observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
  public updatePrivateUser(body: UserDto,  observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling updateUser.');
    }

    let headers = this.defaultHeaders;

    // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<UserDto>('put',`${this.basePath}/v1/user/private`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }


  public deleteUserAdmin(email: string, observe?: 'body', reportProgress?: boolean): Observable<any>;
  public deleteUserAdmin(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
  public deleteUserAdmin(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
  public deleteUserAdmin(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (email === null || email === undefined) {
      throw new Error('Required parameter email was null or undefined when calling deleteUser.');
    }

    let headers = this.defaultHeaders;

       // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    return this.httpClient.request<any>('delete',`${this.basePath}/v1/user/admin/${encodeURIComponent(String(email))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param email
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */


  public findByEmailAdmin(email: string, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
  public findByEmailAdmin(email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
  public findByEmailAdmin(email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
  public findByEmailAdmin(email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (email === null || email === undefined) {
      throw new Error('Required parameter email was null or undefined when calling findByEmail.');
    }

    let headers = this.defaultHeaders;

       // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    return this.httpClient.request<UserDto>('get',`${this.basePath}/v1/user/admin/${encodeURIComponent(String(email))}`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   * this is the list of user
   * Get endpoint for user
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public getAll(observe?: 'body', reportProgress?: boolean): Observable<Array<UserDto>>;
  public getAll(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<UserDto>>>;
  public getAll(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<UserDto>>>;
  public getAll(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    let headers = this.defaultHeaders;

       // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
    ];

    return this.httpClient.request<Array<UserDto>>('get',`${this.basePath}/v1/user/admin/all-users`,
      {
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }

  /**
   *
   *
   * @param body
   * @param email
   * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
   * @param reportProgress flag to report request and response progress.
   */
  public updateUserAdmin(body: UserDto, email: string, observe?: 'body', reportProgress?: boolean): Observable<UserDto>;
  public updateUserAdmin(body: UserDto, email: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<UserDto>>;
  public updateUserAdmin(body: UserDto, email: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<UserDto>>;
  public updateUserAdmin(body: UserDto, email: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

    if (body === null || body === undefined) {
      throw new Error('Required parameter body was null or undefined when calling updateUser.');
    }

    if (email === null || email === undefined) {
      throw new Error('Required parameter email was null or undefined when calling updateUser.');
    }

    let headers = this.defaultHeaders;

       // authentication (bearerAuth) required
    if (this.CookiesService.get("token")) {
      const accessToken = typeof this.configuration.accessToken === 'function'
        ? this.CookiesService.get("token")
        : this.CookiesService.get("token");
      headers = headers.set('Authorization', 'Bearer ' + accessToken);
    }
    // to determine the Accept header
    let httpHeaderAccepts: string[] = [
      '*/*'
    ];
    const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
    if (httpHeaderAcceptSelected != undefined) {
      headers = headers.set('Accept', httpHeaderAcceptSelected);
    }

    // to determine the Content-Type header
    const consumes: string[] = [
      'application/json'
    ];
    const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
    if (httpContentTypeSelected != undefined) {
      headers = headers.set('Content-Type', httpContentTypeSelected);
    }

    return this.httpClient.request<UserDto>('put',`${this.basePath}/v1/user/admin/${encodeURIComponent(String(email))}`,
      {
        body: body,
        withCredentials: this.configuration.withCredentials,
        headers: headers,
        observe: observe,
        reportProgress: reportProgress
      }
    );
  }
}
