/**
 * OpenAPi WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ObjectId } from './objectId';

export interface InterestArea { 
    id?: ObjectId;
    userId: string;
    name: string;
    geometry: string;
    shapefileData?: Array<string>;
    type?: InterestArea.TypeEnum;
    sensorList?: Array<ObjectId>;
}
export namespace InterestArea {
    export type TypeEnum = 'GEOJSON' | 'JSON' | 'PHOTO' | 'RUSTER';
    export const TypeEnum = {
        GEOJSON: 'GEOJSON' as TypeEnum,
        JSON: 'JSON' as TypeEnum,
        PHOTO: 'PHOTO' as TypeEnum,
        RUSTER: 'RUSTER' as TypeEnum
    };
}