/**
 * OpenAPi WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export enum payloadType{
  image,
  raster,
  json,
  shapefile
}

export interface NewSensorDto {
    companyName?: string;
    password?: string;
    description?: string;
    userId?: string;
    payloadType?: payloadType;
    type?: string;
    sensorId?: string;
    interestAreaId?: string;
    token?: string;

}
