/**
 * OpenAPi WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InterestAreaDto } from './interestAreaDto';
import { SensorDto } from './sensorDto';

export interface SensorAndAreas { 
    sensorDtoList?: Array<SensorDto>;
    areaDtoList?: Array<InterestAreaDto>;
}