/**
 * OpenAPi WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SensorDataDto {
  id?: string;
  userId?: string;
  dataType?: string;
  sensorId?: string;
  date?: Date;
  timestamp?: Date;
  latitude?: number;
  longitude?: number;
  payload?: { [key: string]: any };
}
