/**
 * OpenAPi WManager
 * OpenApi documentation for Spring Security
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserPreferenceDto {
  id?: string;
  userId: string;

  // Gruppi di impostazioni (Oggetti, non booleani!)
  uiSettings?: UISettingsDto;
  mapSettings?: MapSettingsDto;
  analyticsSettings?: AnalyticsSettingsDto;

  // Altri campi
  favoriteAreaIds?: string[];
}

// --- Sotto-interfacce per la struttura gerarchica ---

export interface UISettingsDto {
  theme: string;             // "dark", "light", "glass"
  sidebarCollapsed: boolean;
  language: string;          // "it", "en"
}

export interface MapSettingsDto {
  center: number[];          // [lat, lng]
  zoomLevel: number;
  dataMode: string;          // "REAL_TIME" o "LATEST"
  refreshIntervalMinutes: number;
  activeSensorTypes: string[];
  showOverlayLayers: boolean;
}

export interface AnalyticsSettingsDto {
  showSmoothTrend: boolean;
  highlightAnomalies: boolean;
  forecastWindow: string;    // "+1h", "+12h", ecc.
}
