# Usa 127.0.0.1 per evitare ambiguità su Windows
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/postgresql
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

# Forza il dialetto (aiuta Hibernate a saltare un controllo iniziale)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Rimuovi o commenta qualsiasi riferimento a MongoDB (spring.data.mongodb...)
# Importante: se non hai ancora creato le tabelle, questo aiuta a evitare errori di avvio
spring.jpa.generate-ddl=true
# App config
spring.application.name=WManager

spring.data.redis.host=192.168.15.34
spring.data.redis.port=6379


#server in ascolto sulla porta 8010
server.port=8010

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB


spring.main.allow-bean-definition-overriding=true
jwt.secret=mySecretKey
jwt.expirationMs=36000000
jwt.refreshExpirationMs=360000000000


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cose7697@gmail.com
spring.mail.password=cqlqkxypntxeuugw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
